/*
 * @Author - Alex Greco 2/18/2016
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Euler2 {
	static int curNum1 ;
	static int curNum2 ;
	
	public static void main(String[] args){
		long startTime = System.currentTimeMillis();

		System.out.println(fibonacci());

		long endTime = System.currentTimeMillis();

		System.out.println("That took " + (endTime - startTime) + " milliseconds");
	}
	
	public static boolean isEven(int n){
		if(n % 2 == 0) return true;
		else return false;
	}

	public static int fibonacci(){
		int totalSum = 0;
		curNum1 = 1;
		curNum2 = 2;
		while(curNum1 <4000000 || curNum2 < 4000000){
			if(isEven(curNum1)){
				totalSum += curNum1;
			}
			int temp = curNum1;
			curNum1 = curNum2;
			curNum2 = curNum2 + temp;
		}
		return totalSum;
	}
}
